http:
  middlewares:
    middlewares-authelia:
      forwardAuth:
        # TODO Load that port
        address: "http://authelia:{{ Authelia.Port }}/api/verify?rd=https://authelia.{{ Domain }}"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
