log:
  level: TRACE

accessLog:
  filters:
    statusCodes:
      - "204-209"
      - "400-499"
      - "500-599"

api:
  debug: true
  # insecure: false TODO swap this comment with debug
  dashboard: true

certificatesResolvers:
  main:
    acme:
      # TODO secret not replace
      email: "{{ cf_api_email }}"
      storage: "/letsencrypt/acme.json"
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: "90"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    # can define a diff entrypoint for nonauthenticated?

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_public
  # file:
  #   directory: /.config/conf.d
  #   watch: true