tags:
  - latest
  - nightly
vars: 
  - media_dir
  - install_dir
  - domain
  - kavita_token
  - kavita_port
files:
  - name: appsettings.json
    src: "./cmd/install/kavita/files"
    dest: "{{ InstallDir }}/kavita/config"
    
  - name: docker-compose.yml
    src: "./cmd/install/kavita"
    dest: "{{ InstallDir }}/kavita"

addons:
  - roast: kavita_email
