tags:
  - latest
  - nightly
vars:
  - Port: "5000"
dirs: 
  - name: books
    dest: "{{ MediaDir }}"
  - name: comics
    dest: "{{ MediaDir }}"
  - name: manga
    dest: "{{ MediaDir }}"
files:
  - name: appsettings.json
    src: "./roasts/kavita/files"
    dest: "{{ InstallDir }}/kavita/config"
  - name: docker-compose.yml
    src: "./roasts/kavita"
    dest: "{{ InstallDir }}/kavita"
