---
version: "3"
services:
  kavita:
    image: "jvmilazz0/kavita:{{ tag }}"
    container_name: kavita
    volumes:
      - "{{ MediaDir }}/manga:/manga"
      - "{{ MediaDir }}/comics:/comics"
      - "{{ MediaDir }}/books:/books"
      - "{{ InstallDir }}/kavita/config:/kavita/config"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_public
      - "traefik.http.routers.kavita.rule=Host(`kavita.{{ Domain }}`)"
      - "traefik.http.routers.kavita.entrypoints=https"
      - "traefik.http.services.kavita.loadbalancer.server.port={{ Port }}"
    restart: "{{ Restart }}"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
